<?php
/**
 * TL_ROOT/system/modules/catalognotelist/languages/de/tl_catalog_fields.php 
 * 
 * Contao extension: catalognotelist 2.0.0 beta1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2010 CyberSpectrum 
 * License   : LGPL 
 * Author    : Christian Schiffler (Xtra), http://www.cyberspectrum.de 
 * Translator: Joachim Scholtysik (jscholtysik) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['hidden'] = "Versteckt";
?>
